### ISSUE TITLE
New Jekyll site

### ISSUE THREAD

**Issue by raelgc** [cloudsponge/cloudsponge.github.io#1]
New Jekyll site for public pages, like discussed during scrums.

**Comment by dangerouse** [comment]
We are considering using the [ProUI template](https://github.com/cloudsponge/assets/tree/master/ProUI-template).

**Comment by raelgc** [comment]
Spreadsheet with mapping of existing public pages: [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1kdwyPC0ZD9w_tXMXzf0-0ZfIRs7UIHsoQCFzUjKoAh8)

For URLs, [appears](https://github.com/jekyll/jekyll/issues/156) that we probably can use friendly URLs omitting the `.html` extension.

**Comment by raelgc** [comment]
Screenshot for above commit:

![contact_sources_first_draft](https://cloud.githubusercontent.com/assets/263302/7689214/0501d000-fd81-11e4-9bea-d48c87d0413d.png)

**Comment by raelgc** [comment]
Some important issues raised by @circuitfive:

1. develop a convention for embedding gists in jekyll
2. decide if/how we’re going to embed forms (e.g. sign in/sign up)
3. develop a convention for embedding analytics (segment/google tag manager)
4. develop a convention for embedding dynamic content like status and contact sources
5. figure out asset pipeline/asset management stuff
6. verify that everything works when it’s hosted on Github Pages

**Comment by raelgc** [comment]
Trying to answer some of them.

1. Include gists in jekyll [appears](https://gist.github.com/benbalter/5555251) to be really simple: just use `{% gist <id> %}` 
2. Signin/signup forms: @dangerouse it's the best to answer this, but I think we should keep both in the app.
3. For Analytics and related: @circuitfive suggested to use in the jekyll site just Google Tag Manager (than inside it, include Segment and stuff not supported by Segment... then inside Segment, include Crazyegg, GA, etc)
4. TBD
5. For now, I'm just using a single `cloudsponge.scss` file in `/css` folder. This file is importing all the SASS partials. Of course, we can use a gem for that, but I'm trying to keep the project without plugins usage.
6. Of couse, we need to test the site yet, but until now I'm using just stuff that, in theory, works without hassle in Github Pages (need to be tested as soon as possible, anyway).

**Comment by circuitfive** [comment]
Can we use the left sidebar menu from the ProUI template for our developer documentation?

http://pixelcave.com/demo/proui-frontend/ecom_product_list.php

**Comment by raelgc** [comment]
Found a page with GitHub pages supported plugins: https://pages.github.com/versions/

**Comment by raelgc** [comment]
How to treat 301 redirects: https://help.github.com/articles/redirects-on-github-pages/

**Comment by circuitfive** [comment]
From HipChat...

Jay Gibb:
oh @rael I thought on another thing we need to validate on the jekyll site
right now we're capturing a bunch of data when the user lands on our site (such as UTM parameters, http referrer, etc.)
and we're including that in their account when they sign up, even if they sign up another day
it's pretty important data, we use it to make automatic partner account associations for example
and it shows in in our Accounts CSV export and becomes useful there sometimes
so we need to make sure we handle this data properly and don't lose it with this transition to jekyll

Graeme Rouse:
good call, re: jekyll
we capture that stuff in cookies on our public pages
right now we actually do it on the server side, but it should port pretty easily to javascript code for the client

**Comment by raelgc** [comment]
A lot of specific issues were created to handle new initial launch.

As the proper base ProUI layout was already addressed (with draft home page), I'm closing this issue.
