### ISSUE TITLE
add new Terms of Use section and archive the old terms

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/cloudsponge.github.io#18]

**Comment by circuitfive** [comment]
https://docs.google.com/a/cloudsponge.com/document/d/1K7siGcA-do-Fps_VK_5WQb1mppM9Xlb1M9F52wMG3V0/edit?usp=sharing

**Comment by raelgc** [comment]
@circuitfive In the agreement, we're missing to replace [PHONE] by a real number. Do you know what number will we use?

**Comment by circuitfive** [comment]
(888) 725-9352
