### ISSUE TITLE
Move /blog to prevent conflicts with our current /blog

### ISSUE THREAD

**Issue by dangerouse** [cloudsponge/cloudsponge.github.io#24]
Because this project is the main site project, github pages tries to match any requests coming into `cloudsponge.github.io` here first. If it can't find a match here, it will try to match against any other project's `gh-pages` branch. We rely on this for hosting our blog on the `cloudsponge/blog` project, but since this project has a folder called blog, it matches first. 

Currently the content is identical in both places, but I don't want the new layouts, tracking scripts, etc. to take over until the time is right to switch everything to this one project. So for now, let's rename this /blog directory to /articles to prevent confusion.

**Comment by dangerouse** [comment]
I was way off on this one. It turns out that the organization's gh-pages CNAME takes precedence over all project CNAMEs (or at least invalid ones). So when a request came for github.cloudsponge.io it was being redirected to hyde.cloudsponge.com for any of our projects. The temporary resolution is to modify the nginx config for our web servers to send requests to hyde.cloudsponge.com instead of cloudsponge.github.io. When we change the CNAME for this project, we need to update the config accordingly.

**Comment by dangerouse** [comment]
This has become an issue again since merging #21. Please move blog to blog_new.

**Comment by dangerouse** [comment]
@raelgc see my comment above

**Comment by raelgc** [comment]
@dangerouse got it and I just reverted the merge on https://github.com/cloudsponge/cloudsponge.github.io/pull/32
