### ISSUE TITLE
Resolve spacing issues in documentation layout

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/cloudsponge.github.io#25]
![image](https://cloud.githubusercontent.com/assets/2659746/8336065/9b1146a6-1a56-11e5-8465-45356d5c5ef4.png)

1. navigation needs to be moved over to left margin
1. content needs to be aligned with right margin
1. navigation and content need to move up to top margin
1. space between navigation and content needs to be adjusted

Hopefully the sketch I included above is clear, if you're not sure what I meant then just ask.

**Comment by raelgc** [comment]
![developer_spacing](https://cloud.githubusercontent.com/assets/263302/8859091/95f01294-3151-11e5-93cd-66e08a4cb7c6.png)

@circuitfive Fixed all issues but 3 (it was partially fixed): I moved to up as much as possible using the default ProUI layout.
