### ISSUE TITLE
Add ngnix redirects

### ISSUE THREAD

**Issue by raelgc** [cloudsponge/cloudsponge.github.io#36]
We need the following redirects in our public site:

Developers
1. `/developer/widget` => `/developer#the-contact-importer-widget`
2. `/developer/api` => `/developer#the-contact-importer-api`
3. `/developer/api-diy` => `/developer#do-it-yourself-approach`
4. `/developer/branding` => `/developer#branding`

Pricing
1. `/revenue-sharing` => '/pricing'
2. `/price` => `/pricing`

Examples
1. `/examples` => `/`

Switch
1. `/switch` => ` /plaxo-widget`

Product
1. `/product` => `/`

**Comment by dangerouse** [comment]
### Hosting the nginx proxy ourselves

**Pros**

* SSL/TLS on www
* 301 responses

**Cons**

* because no [CDNs](https://www.fastly.com/customers/github)
* because work for us to set up and manage the proxy

**Comment by raelgc** [comment]
Duplicate of the [ProUI-Migration-Checklist Wiki entry](https://github.com/cloudsponge/sponge/wiki/ProUI-Migration-Checklist).
