### ISSUE TITLE
Test Drive

### ISSUE THREAD

**Issue by raelgc** [cloudsponge/cloudsponge.github.io#50]
Work based on `/contact-importers`.

**Comment by raelgc** [comment]
![cloudsponge - after testdrive](https://cloud.githubusercontent.com/assets/263302/8810664/e414d946-2fc6-11e5-8df8-31b15e89e7df.png)

@dangerouse and @circuitfive This is an initial idea when the user click on "next" after contact importing using our widget in the `/contact-importers' page.

Maybe it's missing the rebrand feature. 

But maybe this page is becoming too polluted, almost duplicating all the info from the homepage.

**Comment by dangerouse** [comment]
I like this a lot. Nice work!

1. I think this could make a sweet landing page. I'm not sure where the traffic will come from exactly, but I think it should not require the user to have done the import before they arrive here.
1. we should consider a single column layout with more whitespace between the 4 sections, like the home page. I agree that maybe this is an alternate home/landing page that we could AB test.
1. the contact json could be only the first part of the data. if the user clicks then we launch a modal with the full json. 2 reasons for this: 
  * I don't want a long display but a scrolling textarea will mess with the window scrolling and, more importantly,
  * I want to track 'interest' in the data to correlate with our sign ups/conversions
1. more is too general of a url. consider /product (!) or something like that

**Comment by raelgc** [comment]
Loved all the ideas!

Just like we discussed yesterday, if the idea is to make this a `/product` landing page, so we should consider a better title instead of "And now what?". Something like "What can I do with CloudSponge?".

**Comment by raelgc** [comment]
@dangerouse proposal: 

![](https://s3.amazonaws.com/uploads.hipchat.com/8338/18668/KNmimdhZdYCgT3l/upload.png)
